### ISSUE TITLE
Feature request: Notifications

### ISSUE THREAD

**Issue by anaelleltd** [polkachu/validator-resources#8]
Hi there,

The [Validator Leaderboard](https://polkachu.com/kusama/thousand_validators) is a great resource that I have been using myself and recommending to people as well.

I'm wondering whether it would be possible to allow people/visitors to subscribe to email notifications about a selection of validators from the leaderboard? That way, if validators become inactive or experience notable changes of circumstances, we can get prompted to take action.

This is just an idea that I think could further support Polkadot-JS users when staking.
Cheers! :)

**Comment by husonghua** [comment]
Hey, thanks for the suggestion. The feature is on the roadmap. We plan to enable email notifications for both nominators and validators:

For nominators:
- When a validator becomes inactive or experience notable changes. 
- When a validator has substantial delays in payout

For validators:
- When a large nominator joins or leaves 
- When a validator becomes newly active or inactive
- When era points substantially decrease over a period of time

We will probably get other ideas when we start coding.

That said, we are taking a little break on adding new polkachu.com features. Currently, we are focusing on expanding our validation operations. We will be back at adding new features (including the email notification feature) by the end of this year. 

Polkachu

**Comment by husonghua** [comment]
Close the issue as we have the requested feature on the roadmap.
